name: recommendation
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  eva_icons_flutter: ^3.0.0
  ionicons: ^0.1.2
  http: ^0.13.3
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.2.2
  firebase_core: ^1.3.0
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  flutter_svg: ^0.22.0
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Medium
      fonts:
        - asset: fonts/test-calibre-medium.ttf
    - family: Regular
      fonts:
        - asset: fonts/test-calibre-regular.ttf
    - family: Light
      fonts:
        - asset: fonts/test-calibre-light.ttf
    - family: Akaya
      fonts:
        - asset: fonts/Akaya.ttf
